Fix NoMethodError on duplicate constants
```rbs
Foo: String
Foo: String
```

```bash
$ rbs -I. validate
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/errors.rb:309:in `initialize': undefined method `location' for #<RBS::Environment::SingleEntry:0x000055dc26ebecb0 @name=#<RBS::TypeName:0x000055dc26ebedc8 @namespace=#<RBS::Namespace:0x000055dc26ebee18 @path=[], @absolute=true>, @name=:Foo, @kind=:class>, @decl=#<RBS::AST::Declarations::Constant:0x000055dc26ebf728 @name=#<RBS::TypeName:0x00005
5dc26ebf868 @namespace=#<RBS::Namespace:0x000055dc26ebf8b8 @path=[], @absolute=false>, @name=:Foo, @kind=:class>, @type=#<RBS::Types::ClassInstance:0x000055dc26ebf9a8 @name=#<RBS::TypeName:0x000055dc26ebfd40 @namespace=#<RBS::Namespace:0x000055dc26ebfd90 @path=[], @absolute=false>, @name=:String, @kind=:class>, @args=[], @location=#<RBS::Location:380 @buffer=test.rbs, @pos=5...11, source='String', start_line=1, start_c
olumn=5>>, @location=#<RBS::Location:400 @buffer=test.rbs, @pos=0...11, source='Foo: String', start_line=1, start_column=0>, @comment=nil>, @outer=[]> (NoMethodError)                                                     from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment.rb:129:in `new'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment.rb:129:in `cache_name'                                                                                               from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment.rb:185:in `insert_decl'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment.rb:197:in `<<'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment_loader.rb:131:in `block (2 levels) in load'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment_loader.rb:130:in `each'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment_loader.rb:130:in `block in load'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment_loader.rb:127:in `each'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment_loader.rb:127:in `load'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment.rb:123:in `block in from_loader'
        from <internal:kernel>:90:in `tap'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/environment.rb:122:in `from_loader'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/cli.rb:387:in `run_validate'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/lib/rbs/cli.rb:92:in `run'
        from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.8.0/gems/rbs-0.6.0/exe/rbs:7:in `<top (required)>'
        from /home/pocke/.rbenv/versions/trunk/bin/rbs:23:in `load'
        from /home/pocke/.rbenv/versions/trunk/bin/rbs:23:in `<main>'

```