Fix `rbs prototype rb` with argument-less FCALL
```
NoMethodError: undefined method `children' for nil:NilClass
  /home/pocke/ghq/github.com/ruby/ruby-signature/lib/ruby/signature/prototype/rb.rb:136:in `process'
  /home/pocke/ghq/github.com/ruby/ruby-signature/lib/ruby/signature/prototype/rb.rb:231:in `block in process'
  /home/pocke/ghq/github.com/ruby/ruby-signature/lib/ruby/signature/prototype/rb.rb:256:in `block in each_node'
  /home/pocke/ghq/github.com/ruby/ruby-signature/lib/ruby/signature/prototype/rb.rb:254:in `each'
  /home/pocke/ghq/github.com/ruby/ruby-signature/lib/ruby/signature/prototype/rb.rb:254:in `each_node'
  /home/pocke/ghq/github.com/ruby/ruby-signature/lib/ruby/signature/prototype/rb.rb:262:in `each_child'
  /home/pocke/ghq/github.com/ruby/ruby-signature/lib/ruby/signature/prototype/rb.rb:230:in `process'
  /home/pocke/ghq/github.com/ruby/ruby-signature/lib/ruby/signature/prototype/rb.rb:231:in `block in process'

 (snip)
```

The error caused with the following code.

```ruby
foo()
foo{}
```

In the real world, I met the error with the following code.

```ruby
included do
  do_something
end
```